/// A block is an atomic piece of data network participates are agreed on.
///
/// A block has:
/// - transactional data: a sequence of transactions, where a transaction is an atomic state update.
/// Some metadata is possible as well(transactions Merkle tree root, state Merkle tree root etc).
///
/// - consensus data to check whether block was generated by a right party in a right way. E.g.
/// "baseTarget" & "generatorSignature" fields in the Nxt block structure, nonce & difficulty in the
/// Bitcoin block structure.
///
/// - a signature(s) of a block generator(s)
///
/// - additional data: block structure version no, timestamp etc
class BlockInformation {
  /// the height of the block above the genesis block
  final int height;

  /// The id of the block
  final String blockId;

  /// The id of the parent block
  final String parentBlockId;

  /// [BlockNum] of the block
  final BlockNum blockNumber;

  /// Timestamp referring to when the block was originally forged
  final DateTime timestamp;

  ///

}
