# This workflow will test the BramblDart application

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Step to setup Flutter, we will need this to run the code coverage in a later step
      - name: Install Flutter
        uses: subosito/flutter-action@v1.3.2

      # Next, we install dependencies
      - name: Install dependencies
        run: dart pub get
      # Step to run tests with coverage  
      - name: test bramblDart
        run: flutter test --coverage
      # Step to publish coverage results
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

        
      
      
